<?php

include_once('recruiter_search_solr.features.inc');

/**
 * Implements hook_default_search_api_index_alter().
 */
function recruiter_search_solr_default_search_api_index_alter(&$configs) {
  // Enable the solr server for the job and resume search.
  $indexes = array('job_search', 'resume_search');
  foreach ($indexes as $index) {
    if (isset($configs[$index])) {
      $configs[$index]->server = "solr_server";
      // Disable the default tokenizer as Solr does a better job.
      $configs[$index]->options['processors']['search_api_tokenizer']['status'] = FALSE;
    }
  }
}
