<?php

/**
 * Sets the i18n_list_default display type for all i18n fields
 * that have list_default as their default display type.
 *
 * Implements hook_field_default_fields_alter().
 */
function recruiter_i18n_field_default_fields_alter(&$fields) {
  $i18n_types = i18n_field_type_info();
  foreach ($fields as $field_name => &$field) {
    if (array_key_exists($field['field_config']['type'], $i18n_types)) {
      foreach ($field['field_instance']['display'] as $display_name => &$display) {
        if ($display['type'] == 'list_default') {
          $display['type'] = 'i18n_list_default';
          $display['module'] = 'i18n_field';
        }
      }
    }
  }
}
