<?php

/**
 * @file
 * Recruiter registration feature.
 */

include_once('recruiter_register.features.inc');

/**
 * Implements hook_block_info().
 */
function recruiter_register_block_info() {
  $blocks['applicant_info'] = array(
    'info' => t('Registration information for applicants'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['recruiter_info'] = array(
    'info' => t('Registration information for recruiter'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function recruiter_register_block_view($delta) {
  switch ($delta) {
    case 'applicant_info':
      return array(
        'subject' => t('You are about to sign up as @applicant.', array('@applicant' => t('applicant'))),
        'content' => array(
          'body' => array(
            '#markup' => t('Sign up as @recruiter instead? Click <a href="!url">here</a>!', array('!url' => url('user/register/recruiter'), '@recruiter' => t('recruiter'))),
          ),
        ),
      );
    case 'recruiter_info':
      return array(
        'subject' => t('You are about to sign up as @recruiter.', array('@recruiter' => t('recruiter'))),
        'content' => array(
          'body' => array(
            '#markup' => t('Sign up as @applicant instead? Click <a href="!url">here</a>!', array('!url' => url('user/register'), '@applicant' => t('applicant'))),
          ),
        ),
      );
  }
}
