<?php

include_once('recruiter_common.features.inc');

/**
 * Implements hook_init().
 */
function recruiter_common_init() {
  // Add the custom colorbox-behaviour if colorbox is enabled.
  if (!drupal_installation_attempted() && _colorbox_active()) {
    drupal_add_js(drupal_get_path('module', 'recruiter_common') . '/colorbox.js');
  }
}

/**
 * Implements hook_menu().
 */
function recruiter_common_menu() {
  $items['admin/recruiter'] = array(
    'title' => 'Recruiter',
    'description' => 'Administer recruitment content.',
    'position' => 'right',
    'weight' => -11,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' =>  '/system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  return $items;
}
