<?php

/**
 * @file
 * Recruiter common module file.
 */

/**
 * Implements hook_menu().
 */
function recruiter_common_menu() {
  $items['admin/recruiter'] = array(
    'title' => 'Recruiter',
    'description' => 'Administer recruitment content.',
    'position' => 'right',
    'weight' => -11,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' =>  '/system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/recruiter'] = array(
    'title' => 'Recruiter',
    'description' => 'Configure recruiter features',
    'position' => 'right',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' =>  '/system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  return $items;
}

/**
 * Implements hook_preprocess().
 */
function recruiter_common_preprocess_entity(&$variables) {
  // Remove empty field collections for users without edit permission.
  if ($variables['entity_type'] == 'profile2' && !profile2_access('edit', $variables['profile2'])) {
    foreach ($variables['content'] as &$item) {
      if (isset($item['#field_type']) && $item['#field_type'] == 'field_collection') {
        if (empty($item['#items'])) {
          $item['#access'] = FALSE;
        }
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function recruiter_common_form_field_collection_item_form_alter(&$form, &$form_state, $form_id) {
  // Add help text for description items.
  if (isset($form_state['field_collection_item'])) {
    $entity = $form_state['field_collection_item'];
    $instance = field_info_instance($entity->hostEntityType(), $form['field_name']['#value'], $entity->hostEntityBundle());
    if (!empty($instance['description'])) {
      $form['help'] = array(
        '#weight' => -999,
        '#markup' => '<div class="description field-collection-item-form-description">' . filter_xss_admin($instance['description']) . '</div>',
      );
    }
  }
}


