<?php
/**
 * @file
 */

// Drupal needs this blank file.

include_once('recruiter_admin.features.inc');

/**
 * Implements hook_user_view().
 */
function recruiter_admin_user_view($account, $view_mode, $langcode) {
  // Add some useful administration links.
  if ($view_mode == "full" && user_access('administer users')) {
    $items = array();
    // By default we do not have any links, but allow modules, like the resume
    // feature, to add items.
    drupal_alter('recruiter_admin_links', $items, $account);

    if (count($items)) {
      $account->content['summary']['admin_links'] =  array(
        '#title' => t('Admin links'),
        '#theme' => 'item_list',
        '#items' => $items,
        '#weight' => 10,
      );
    }
  }
}
